[gdrive]
file_id = "1UnHZgOBvNf3Y0ANHCvIN4IThLTgxH6iII--3jB-ZJ4E"

[gdrive.service_account]
type = "service_account"
project_id = "depo-uygulamasi-streamlit"
private_key_id = "c643db3e24c3b1dde6cfddf84111b2bccb7b4c75"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCWmxNt8ZSazEV0
D0zR4efm9oLuvVKG+mfVHeLo4PXSH0otq/pRm7wZuZAujg66nX/piUMrqA8vdOCT
V7XbdmNE0FHEDgslOiPdTDMz9RNbYrnlKjS9/ozPRSdtRznRdI/0ctXY5uMrYPa0
GDmlMoS++4sQOqrbe9TzRV7jsG5uxqlin4a4QkEt4hzc73iNYvVHBeiB2aDbGSxs
4SDsIC/r66dhOAWC+bYZ7KZMXknkITj4vyXvxbqJen4jHVvVyhk0PMcv8x1ZZlQG
gIyruZt+zvcI3bHlPRus2CQ2g5AbDpdjJ8kZ9RCkkZtB16XQTdmkd/YFyKOh542J
3Fl4wIKfAgMBAAECggEAECnFfIusSK66l3ma432Mr19ubuPXqw/Nu/QQqbCXAT2F
bwBhhYeiuNoO7MgnMYT8uNoX4OQQ+SVggr+rj0mV3slCtTlSneSu+62VYzKeqLSg
QcV1UpyyjP4dfJ9jx6RsXK5EYBprb/jgkTR2X1HcKEkDxDKfqp2QHamoxOPm/jFe
xYmyOwQ8viz6rN2hshkwlmE7oFZNWDqyisNdhn+2pC4NpHyiK/NP2oUxLPUFcZfR
zPTu/KP72+FZxuYzBoBbQM/H1znR3xZ69htJO/Ln0GspgqTNfPZQRtgNKs50mbg/
o63NybhoBJG+y4T8b7i002b9+Df5k+9tG9dMocChdQKBgQDNJnD5OPa9/YFvWDqg
BXlyD5SaC829QwTYAJnsv9e97S1fRO9NbVn203svNmL/A9fCIhuJcAQv/VTWY23U
ge96KjsG/OMUDPp2a3QjMKwGzhiTshGqt+pszcraRPO0PmrQK7J3tSQbYZbGwONN
3Rly2/IRGNohnW/yWEwsyZpp7QKBgQC775XD+eZ22n2ChUu6dVqOPg4kWNJylFjf
xW/CDetDZG4a4qzlj0zzWPe+5GbCSpNWFsyGHK8NKfU5F5FSWBSTGDynd6ETZvEv
3DoYq5VsiEamrlbS+Ug6d5lYU2AEntMU328BFRll6XgrPzX4KcJLX0l6v0FRqr9z
6UgXPotdOwKBgExytMrKpXgrTd6WPFKBd74/fBrjpymOHfH4V2PYIadPCQdlgt+R
jmLicBcp5z4symw3lZdjvMu9Va4Go1j7iqg1sIVsG5rPM06JwF+UtaZbiuEPDHJX
0u30ylEIPODAGcG1Zu4g/HGPrkYmfw33BJK+z7f7UN4R8zOWH9zYy8gJAoGBAKYn
Qpx6EvRfZPmBCZu25zG80Vn3IU/lsdFcx9qj3ay+XM3uO/fUwq6eqKIfYm5B6pMB
Ix8quuUDhGdOW8+WSdJmajGRBVqW94NdzAtFn5zNutDgb6ikdeQjGvLI+6n6FRpu
E8C8O7ErQW/Suc9GdB2ZB+i6sHAYap160J6kUChDAoGAErKq8l2uSbTnITj4BNqm
nA+epMllGAtk+nCeMcf+AiAekWunWFFsZFGXop+9IgmdAa/WPx1HVCQG3D57TLsy
kFG0jmgSk6KLM0wkvjw1HTa3r4exKgT+eyvK/GFiKdLzU9XYuLzK9Q+EQpOMe6OJ
Po7HLW6i7qrzH/NzoTaZecs=
-----END PRIVATE KEY-----"""
client_email = "streamlit-depo-app@depo-uygulamasi-streamlit.iam.gserviceaccount.com"
client_id = "102218415403735481109"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-depo-app%40depo-uygulamasi-streamlit.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
