[telegram]
bot_token = "8742500663:AAEQL3yWpCvWz9vylcQ3bzP0TT-GyFYsCOc"
chat_id = "1672833942"
report_time = "14:42"  # Hangi saatte mesaj atsın istiyorsanız (Örn: "09:00", "23:30")

seller_id = "293930"
api_key = "cXN5znfSh8IDPyzh5caG"
api_secret = "rYcCUq99POkxYef2PDMv"